name: Yasowant
favicon: null
layout_spectrum: 0.7639896131586283
typography_spectrum: 0.533269781852141
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9629930325318128
  lightness: 0.7153658329043537
  saturation: 0.25167941953986883
  rhythmicContrast: 0.9595707322005183
purpose: []
